/*
  ____                 __               __   _ __
 / __ \__ _____ ____  / /___ ____ _    / /  (_) /
/ /_/ / // / _ `/ _ \/ __/ // /  ' \  / /__/ / _ \
\___\_\_,_/\_,_/_//_/\__/\_,_/_/_/_/ /____/_/_.__/
  Part of the Quantum OS Project

Copyright 2023 Gavin Kellam

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute,
sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

pub mod command;
pub mod data;
pub mod drive_head;
pub mod error;
pub mod feature;
pub mod sector;
pub mod status;

pub const PRIMARY_BUS_IO_BASE: usize = 0x1F0;
pub const SECONDARY_BUS_IO_BASE: usize = 0x170;

pub const PRIMARY_BUS_CONTROL_BASE: usize = 0x3F6;
pub const SECONDARY_BUS_CONTROL_BASE: usize = 0x376;

/// # R/W: Data Register (16-bit / 16-bit)
/// Read/Write PIO data bytes
pub const DATA_REGISTER_OFFSET_FROM_IO_BASE: usize = 0;

/// # R: Error Register (8-bit / 16-bit)
/// Used to retrieve any error generated by the last ATA command executed.
pub const ERROR_REGISTER_OFFSET_FROM_IO_BASE: usize = 1;

/// # W: Features Register (8-bit / 16-bit)
/// Used to control command specific interface features.
pub const FEATURES_REGISTER_OFFSET_FROM_IO_BASE: usize = 1;

/// # R/W: Sector Count Register (8-bit / 16-bit)
/// Number of sectors to read/write (0 is a special value).
pub const SECTOR_COUNT_OFFSET_FROM_IO_BASE: usize = 2;

/// # R/W: Sector Number Register (LBAlo) (8-bit / 16-bit)
/// This is CHS / LBA28 / LBA48 specific.
pub const SECTOR_NUM_LOW_OFFSET_FROM_IO_BASE: usize = 3;

/// # R/W: Cylinder Low Register / (LBAmid) (8-bit / 16-bit)
/// Partial Disk Sector address.
pub const SECTOR_NUM_MID_OFFSET_FROM_IO_BASE: usize = 4;

/// # R/W: Cylinder High Register / (LBAhi)	(8-bit / 16-bit)
/// Partial Disk Sector address.
pub const SECTOR_NUM_HIGH_OFFSET_FROM_IO_BASE: usize = 5;

/// # R/W: Drive / Head Register (8-bit / 8-bit)
/// Used to select a drive and/or head. Supports extra address/flag bits.
pub const DRIVE_HEAD_OFFSET_FROM_IO_BASE: usize = 6;

/// # R: Status Register (8-bit / 8-bit)
/// Used to read the current status.
pub const STATUS_REGISTER_OFFSET_FROM_IO_BASE: usize = 7;

/// # W: Command Register (8-bit / 8-bit)
/// Used to send ATA commands to the device.
pub const COMMAND_OFFSET_FROM_IO_BASE: usize = 7;

/// # R: Alternate Status Register (8-bit / 8-bit)
/// A duplicate of the Status Register which does not affect interrupts.
pub const ALTERNATE_STATUS_REGISTER_OFFSET_FROM_CONTROL_BASE: usize = 0;

/// # W: Device Control Register (8-bit / 8-bit)
/// Used to reset the bus or enable/disable interrupts.
pub const DEVICE_CONTROL_REGISTER_OFFSET_FROM_CONTROL_BASE: usize = 0;

/// # R: Drive Address Register (8-bit / 8-bit)
/// Provides drive select and head select information.
pub const DRIVE_ADDRESS_REGISTER_OFFSET_FROM_CONTROL_BASE: usize = 1;

pub trait RegisterPort {
    fn io_port()
}